sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '10'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm install -g npm@latest
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10"
